# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.6'

# Web server
gem 'puma', '~> 4.3'
gem 'rack', '>= 2.0'

group :test do
  gem 'rack-test', '~> 1.1'
  gem 'rspec', '~> 3.9'
end